# Site settings
title: Valdir Viana
email: viana.valdir@gmail.com
description: > # this means to ignore newlines until "email:"
   Desenvolvimento Full-Stack | Aprendizado | Técnologia
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://valdirviana.github.io" # the base hostname & protocol for your site
twitter_username: valdir_viana
github_username:  valdirviana
permalink: pretty
apresentacao: Programação com um pouco de nerdices em geral
paginate: 7
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
highlighter: pygments

#blog logo
logo: "/assets/images/logovaldirviana3002.jpg"
# blog cover
cover: "/assets/images/posts/post2.svg"