# Site settings
title: Valdir Viana
email: viana.valdir@gmail.com
description: > # this means to ignore newlines until "email:"
   Desenvolvimento Full-Stack | Aprendizado | TÃ©cnologia
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://valdirviana.github.io" # the base hostname & protocol for your site
twitter_username: valdir_viana
github_username:  valdirviana
permalink: pretty

# Build settings
markdown: kramdown
highlighter: pygments

#blog logo
logo: "/assets/images/logovaldirviana3002.jpg"
# blog cover
cover: "/assets/images/green-polygon-14420.jpg"